import Mathlib.Algebra.Module.LinearMap.Star
import Mathlib.Algebra.Order.Nonneg.Basic
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.LinearAlgebra.SesquilinearForm.Basic
import Jordan.Triality.Basic

/-!
# Gauged and normed trialities

A `GaugedTriality` is a `Triality` whose three modules each carry a *gauge* `Mᵢ → Γ` into an
ordered commutative monoid `Γ`, along with a multiplicative gauge `R →* Γ` on scalars, such that

* each module gauge is homogeneous, `gauge (r • m) = gauge r * gauge m`, and
* the triality product is bounded by the gauges, `gauge (t x y z) ≤ gauge x * gauge y * gauge z`.

This is the shape of a *normed* triality (Baez, *The octonions*, §2.4) with the norms replaced by
gauges: nothing requires the gauges to come from inner products, or even to be subadditive, and
Baez's further condition that the bound is attained is not imposed at this level.

The special case `NormedTriality` is Baez's notion. The gauges come from inner products: the base
ring `R` plays the role of `ℂ`, with a `star`, and each module carries an `R`-valued inner
product, antilinear in one slot and linear in the other. `R` is a `StarOrderedRing`: its partial
order is the one whose nonnegative cone is generated by the `star s * s` (for `ℂ`, `z ≤ w` iff
`w - z` is a nonnegative real, everything else incomparable), so `0 ≤ ⟪m, m⟫` and
`|t x y z|² ≤ ⟪x,x⟫ ⟪y,y⟫ ⟪z,z⟫` are comparisons inside that cone. The bound is *attained*,
symmetrically in the three slots: fixing any two of `x, y, z`, some nonzero value of the third
gives equality. The gauged triality it induces has
`Γ = {r : R // 0 ≤ r}`, the "nonnegative reals" of `R`, with gauges `‖m‖² = ⟪m, m⟫` and
`|r|² = star r * r`; homogeneity and multiplicativity are derived from sesquilinearity.
-/

/-- A triality with homogeneous gauges `Mᵢ → Γ` on its three modules and a multiplicative gauge
`R →* Γ` on scalars, bounding the triality product: `gauge (t x y z) ≤ gauge x * gauge y * gauge z`.
-/
class GaugedTriality (R : outParam (Type u)) (M1 M2 M3 : Type v) (Γ : outParam (Type w))
  [CommRing R] [StarRing R]
  [AddCommGroup M1] [Module R M1]
  [AddCommGroup M2] [Module R M2]
  [AddCommGroup M3] [Module R M3]
  [CommMonoid Γ] [PartialOrder Γ] extends Triality R M1 M2 M3 where
  /-- The scalar gauge, multiplicative on `R`. -/
  gauge_R : R →* Γ
  gauge_x : M1 → Γ
  gauge_y : M2 → Γ
  gauge_z : M3 → Γ
  /-- Homogeneity: scaling by `r` multiplies the gauge by `gauge_R r`. -/
  gauge_x_smul : ∀ (r : R) (x : M1), gauge_x (r • x) = gauge_R r * gauge_x x
  gauge_y_smul : ∀ (r : R) (y : M2), gauge_y (r • y) = gauge_R r * gauge_y y
  gauge_z_smul : ∀ (r : R) (z : M3), gauge_z (r • z) = gauge_R r * gauge_z z
  /-- The triality product is bounded by the product of the gauges. -/
  gauge_triality_prod_le : ∀ x y z,
    gauge_R (triality_prod x y z) ≤ gauge_x x * gauge_y y * gauge_z z

namespace GaugedTriality

variable {R M1 M2 M3 Γ} [CommRing R] [StarRing R]
  [AddCommGroup M1] [Module R M1]
  [AddCommGroup M2] [Module R M2]
  [AddCommGroup M3] [Module R M3]
  [CommMonoid Γ] [PartialOrder Γ]
  (G : GaugedTriality R M1 M2 M3 Γ)

section Homogeneity

/-! ### Consequences of homogeneity alone

`gauge_x` on the `R`-line through `x` is determined by `gauge_x x` and `gauge_R`. -/

theorem gauge_x_neg (x : M1) : G.gauge_x (-x) = G.gauge_R (-1) * G.gauge_x x := by
  rw [← neg_one_smul R x, G.gauge_x_smul]

theorem gauge_y_neg (y : M2) : G.gauge_y (-y) = G.gauge_R (-1) * G.gauge_y y := by
  rw [← neg_one_smul R y, G.gauge_y_smul]

theorem gauge_z_neg (z : M3) : G.gauge_z (-z) = G.gauge_R (-1) * G.gauge_z z := by
  rw [← neg_one_smul R z, G.gauge_z_smul]

/-- `gauge_x 0 = gauge_R 0 * gauge_x x` for every `x`, so `gauge_R 0 * gauge_x x` does not depend
on `x`. -/
theorem gauge_x_zero_eq (x : M1) : G.gauge_x 0 = G.gauge_R 0 * G.gauge_x x := by
  rw [← G.gauge_x_smul, zero_smul]

theorem gauge_y_zero_eq (y : M2) : G.gauge_y 0 = G.gauge_R 0 * G.gauge_y y := by
  rw [← G.gauge_y_smul, zero_smul]

theorem gauge_z_zero_eq (z : M3) : G.gauge_z 0 = G.gauge_R 0 * G.gauge_z z := by
  rw [← G.gauge_z_smul, zero_smul]

theorem gauge_x_smul_smul (r s : R) (x : M1) :
    G.gauge_x (r • s • x) = G.gauge_R (r * s) * G.gauge_x x := by
  rw [G.gauge_x_smul, G.gauge_x_smul, map_mul, mul_assoc]

theorem gauge_y_smul_smul (r s : R) (y : M2) :
    G.gauge_y (r • s • y) = G.gauge_R (r * s) * G.gauge_y y := by
  rw [G.gauge_y_smul, G.gauge_y_smul, map_mul, mul_assoc]

theorem gauge_z_smul_smul (r s : R) (z : M3) :
    G.gauge_z (r • s • z) = G.gauge_R (r * s) * G.gauge_z z := by
  rw [G.gauge_z_smul, G.gauge_z_smul, map_mul, mul_assoc]

end Homogeneity

section Bound

/-! ### The bound in the other curryings and through the duality isomorphisms -/

variable (x : M1) (y : M2) (z : M3)

theorem gauge_triality_prod_xz_le :
    G.gauge_R (G.triality_prod_xz x z y) ≤ G.gauge_x x * G.gauge_y y * G.gauge_z z :=
  G.gauge_triality_prod_le x y z

theorem gauge_triality_prod_yz_le :
    G.gauge_R (G.triality_prod_yz y z x) ≤ G.gauge_x x * G.gauge_y y * G.gauge_z z :=
  G.gauge_triality_prod_le x y z

/-- The functional `xEquiv₂₃ x hx y ∈ M3ᵛ` is bounded by `gauge_x x * gauge_y y` in the sense that
its value at `z` is bounded by that times `gauge_z z`. -/
theorem gauge_xEquiv₂₃_le (hx : x ≠ 0) :
    G.gauge_R (G.xEquiv₂₃ x hx y z) ≤ G.gauge_x x * G.gauge_y y * G.gauge_z z :=
  G.gauge_triality_prod_le x y z

theorem gauge_yEquiv₁₃_le (hy : y ≠ 0) :
    G.gauge_R (G.yEquiv₁₃ y hy x z) ≤ G.gauge_x x * G.gauge_y y * G.gauge_z z :=
  G.gauge_triality_prod_le x y z

theorem gauge_zEquiv₁₂_le (hz : z ≠ 0) :
    G.gauge_R (G.zEquiv₁₂ z hz x y) ≤ G.gauge_x x * G.gauge_y y * G.gauge_z z :=
  G.gauge_triality_prod_le x y z

end Bound

end GaugedTriality

/-! ## Normed trialities: gauges from inner products

An inner product on an `R`-module is a sesquilinear form `⟪·,·⟫ : M →ₗ⋆[R] M →ₗ[R] R` (antilinear
in the first slot) that is `LinearMap.IsPosSemidef` — Hermitian (`LinearMap.IsSymm`,
`star ⟪m, m'⟫ = ⟪m', m⟫`) and nonnegative (`0 ≤ ⟪m, m⟫`) — and definite. "Nonnegative" refers to
the `StarOrderedRing` order on `R`, whose nonnegative cone `{r // 0 ≤ r}` is generated by the
`star s * s`: the "nonnegative reals" of `R`. That cone is the `Γ` of the induced gauged
triality. -/

section NormedTriality

variable (R : Type u) [CommRing R] [StarRing R] [PartialOrder R]

/-- An `R`-valued inner product on `M`: a sesquilinear form (antilinear in the first slot) that is
positive semidefinite in Mathlib's sense (`LinearMap.IsPosSemidef`: Hermitian and `0 ≤ ⟪m, m⟫`)
and definite. -/
structure InnerProductForm (M : Type v) [AddCommGroup M] [Module R M] where
  toLinearMap : M →ₗ⋆[R] M →ₗ[R] R
  posSemidef : toLinearMap.IsPosSemidef
  definite : ∀ m, toLinearMap m m = 0 → m = 0

namespace InnerProductForm

variable {R} {M : Type v} [AddCommGroup M] [Module R M]

instance : CoeFun (InnerProductForm R M) fun _ => M → M →ₗ[R] R := ⟨fun B => B.toLinearMap⟩

theorem nonneg (B : InnerProductForm R M) (m : M) : 0 ≤ B m m := B.posSemidef.nonneg m

theorem conj_symm (B : InnerProductForm R M) (m m' : M) : star (B m m') = B m' m :=
  B.posSemidef.isSymm.eq m m'

/-- Homogeneity of the diagonal: `⟪r • m, r • m⟫ = (star r * r) ⟪m, m⟫`. -/
theorem smul_self (B : InnerProductForm R M) (r : R) (m : M) :
    B (r • m) (r • m) = star r * r * B m m := by
  show B.toLinearMap (r • m) (r • m) = _
  rw [map_smulₛₗ B.toLinearMap r m, LinearMap.smul_apply, map_smul, smul_eq_mul, smul_eq_mul,
    starRingEnd_apply, mul_assoc]

end InnerProductForm

/-- Baez's normed triality: the modules carry `R`-valued inner products (`InnerProductForm`), for
a `StarOrderedRing R`, with `|t x y z|² ≤ ⟪x,x⟫ ⟪y,y⟫ ⟪z,z⟫` (where `|r|² = star r * r`), and
the bound is attained in each slot: fixing any two of `x, y, z`, some nonzero value of the third
gives equality. -/
class NormedTriality (R : outParam (Type u)) (M1 M2 M3 : Type v)
  [CommRing R] [StarRing R] [PartialOrder R] [StarOrderedRing R]
  [AddCommGroup M1] [Module R M1]
  [AddCommGroup M2] [Module R M2]
  [AddCommGroup M3] [Module R M3] extends Triality R M1 M2 M3 where
  inner_x : InnerProductForm R M1
  inner_y : InnerProductForm R M2
  inner_z : InnerProductForm R M3
  /-- The bound `|t x y z|² ≤ ⟪x,x⟫ ⟪y,y⟫ ⟪z,z⟫`. -/
  normSq_triality_prod_le : ∀ x y z,
    star (triality_prod x y z) * triality_prod x y z ≤ inner_x x x * inner_y y y * inner_z z z
  /-- The bound is attained, symmetrically in the three slots: fixing any two of `x, y, z`, some
  nonzero value of the third gives `|t x y z|² = ⟪x,x⟫ ⟪y,y⟫ ⟪z,z⟫`. -/
  exists_normSq_triality_prod_eq_z : ∀ x y, ∃ z, z ≠ 0 ∧
    star (triality_prod x y z) * triality_prod x y z = inner_x x x * inner_y y y * inner_z z z
  exists_normSq_triality_prod_eq_y : ∀ x z, ∃ y, y ≠ 0 ∧
    star (triality_prod x y z) * triality_prod x y z = inner_x x x * inner_y y y * inner_z z z
  exists_normSq_triality_prod_eq_x : ∀ y z, ∃ x, x ≠ 0 ∧
    star (triality_prod x y z) * triality_prod x y z = inner_x x x * inner_y y y * inner_z z z

namespace NormedTriality

variable {R} [StarOrderedRing R]

/-- The nonnegative cone of `R`, an ordered commutative semiring (Mathlib's `Nonneg`
instances, via `StarOrderedRing.toIsOrderedRing` since `R` is commutative). -/
abbrev Nonneg (R : Type u) [CommRing R] [StarRing R] [PartialOrder R] [StarOrderedRing R] :
    Type u :=
  { r : R // 0 ≤ r }

/-- The squared absolute value `|r|² = star r * r`, as a multiplicative map into the cone. -/
def normSqHom : R →* Nonneg R where
  toFun r := ⟨star r * r, star_mul_self_nonneg r⟩
  map_one' := Subtype.ext (by simp)
  map_mul' r s := Subtype.ext (by
    show star (r * s) * (r * s) = star r * r * (star s * s)
    rw [star_mul]; ring)

@[simp] theorem coe_normSqHom (r : R) : (normSqHom r : R) = star r * r := rfl

variable {M1 M2 M3 : Type v}
  [AddCommGroup M1] [Module R M1]
  [AddCommGroup M2] [Module R M2]
  [AddCommGroup M3] [Module R M3]
  [N : NormedTriality R M1 M2 M3]

/-- A normed triality is a gauged triality with `Γ = {r : R // 0 ≤ r}`, gauges `‖m‖² = ⟪m, m⟫`
and `|r|² = star r * r`. -/
instance toGaugedTriality : GaugedTriality R M1 M2 M3 (Nonneg R) :=
  { N.toTriality with
    gauge_R := normSqHom
    gauge_x := fun x => ⟨N.inner_x x x, N.inner_x.nonneg x⟩
    gauge_y := fun y => ⟨N.inner_y y y, N.inner_y.nonneg y⟩
    gauge_z := fun z => ⟨N.inner_z z z, N.inner_z.nonneg z⟩
    gauge_x_smul := fun r x => Subtype.ext (N.inner_x.smul_self r x)
    gauge_y_smul := fun r y => Subtype.ext (N.inner_y.smul_self r y)
    gauge_z_smul := fun r z => Subtype.ext (N.inner_z.smul_self r z)
    gauge_triality_prod_le := fun x y z => by
      rw [Nonneg.mk_mul_mk, Nonneg.mk_mul_mk, Subtype.mk_le_mk]
      exact N.normSq_triality_prod_le x y z }

end NormedTriality

section CauchySchwarz

/-! ### Cauchy–Schwarz for a nonnegative symmetric bilinear form

Over a commutative star-ordered ring with trivial star. The division-free form is
`0 ≤ B z z * (B u u * B z z - B u z²)`, obtained by expanding `0 ≤ B w w` for
`w = B z z • u - B u z • z`; when `B z z` is a unit it can be cancelled, since its inverse is
`B z z * c²` and hence nonnegative. -/

variable {R : Type u} [CommRing R] [StarRing R] [TrivialStar R] [PartialOrder R] [StarOrderedRing R]
  {M : Type v} [AddCommGroup M] [Module R M] (B : M →ₗ[R] M →ₗ[R] R)
  (hsymm : ∀ u z, B u z = B z u) (hpos : ∀ w, 0 ≤ B w w)
include hsymm hpos

omit [StarRing R] [TrivialStar R] [StarOrderedRing R] in
theorem mul_cauchySchwarz_sub_nonneg (u z : M) :
    0 ≤ B z z * (B u u * B z z - B u z * B u z) := by
  have key : B (B z z • u - B u z • z) (B z z • u - B u z • z) =
      B z z * (B u u * B z z - B u z * B u z) := by
    simp only [map_sub, map_smul, LinearMap.sub_apply, LinearMap.smul_apply, smul_eq_mul]
    rw [hsymm z u]
    ring
  rw [← key]
  exact hpos _

theorem cauchySchwarz_of_isUnit {u z : M} (hz : IsUnit (B z z)) :
    B u z * B u z ≤ B u u * B z z := by
  have h := mul_cauchySchwarz_sub_nonneg B hsymm hpos u z
  have hc : 0 ≤ (↑hz.unit⁻¹ : R) := by
    have : (↑hz.unit⁻¹ : R) = B z z * ((↑hz.unit⁻¹ : R) * ↑hz.unit⁻¹) := by
      rw [← mul_assoc, hz.mul_val_inv, one_mul]
    rw [this]
    exact mul_nonneg (hpos z) (by simpa [star_trivial] using star_mul_self_nonneg (↑hz.unit⁻¹ : R))
  have : B u u * B z z - B u z * B u z =
      (↑hz.unit⁻¹ : R) * (B z z * (B u u * B z z - B u z * B u z)) := by
    rw [← mul_assoc, hz.val_inv_mul, one_mul]
  exact sub_nonneg.mp (this ▸ mul_nonneg hc h)

end CauchySchwarz

end NormedTriality
