/-!
# Structure Algebra

TODO: Define the structure algebra of a Jordan algebra. The expected starting point is the Lie
subalgebra generated by left multiplications and derivations, then prove the standard action
identities needed for the later Jordan constructions.
-/
